# Deletes named local profiles 
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\admalbrechth')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\admneumayrm')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\admobermeierj')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\admangk')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMLytkinO')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMWlodarczykS')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMHudacskoT')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMSzilagyiJ')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMChngE')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMHadiI')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMChintadaS')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMNashatarA')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMpraj')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMaamran')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMhahussin')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMkpoongav')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMknazirah')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMherawi')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADManikya')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMsuyusof')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMsentan')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMsnordin')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMBrodiS')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMIstenesI')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMChanCK')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\HEALBREC')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMZeiskeM')} | Remove-WMIObject
Get-WMIObject -Class Win32_UserProfile | where {($_.LocalPath -eq 'c:\users\ADMFischerM')} | Remove-WMIObject